name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17-jdk]
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew :minecraft:silk:build
      - run: ./gradlew build publishToMavenLocal --stacktrace --warning-mode fail
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
